obj-m += genericfs.o
genericfs-objs := dir.o file.o global.o inode.o namei.o ops.o super.o

dir.o:         dir.c genericfs.h global.h dir.h

file.o:        file.c genericfs.h global.h file.h

global.o:      global.c genericfs.h global.h

inode.o:       inode.c genericfs.h global.h inode.h ops.h

namei.o:       namei.c genericfs.h global.h namei.h

ops.o:         ops.c genericfs.h global.h dir.h file.h inode.h namei.h ops.h super.h

super.o:       super.c genericfs.h global.h inode.h ops.h super.h
